task-5/6
cleannetcode/TssT pull request #18
Opened 2021-07-24 10:36 UTC by coder1coder

#5 и #6

2021-07-24 18:14 UTC, coder1coder commented on TssT.API/Mappings/Profiles/TopicGroupProfile.cs
> +}
лишнее 100%

2021-07-25 12:36 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicGroupRepository.cs
> +            if (existsCount > 0)
похоже на бизнеслогическую валидацию. Данный код следует вынести в сервис

2021-07-25 12:36 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicGroupRepository.cs
> +            if (id < 1)
лучше писать <= default(int)

2021-07-25 12:37 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicGroupRepository.cs
> +            if (existsCount > 0)
также похоже на бизнес логическую валидацию

2021-07-25 12:38 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicGroupRepository.cs
> +            if (id < 1)
<= default(int)

2021-07-25 12:38 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicGroupRepository.cs
> +            if (entry?.Topics.Count > 0)
еще одна бизнес логическая валидация

2021-07-25 12:39 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicRepository.cs
> +            if (existsCount > 0)
еще одна бизнес логическая валидация

2021-07-25 12:40 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicRepository.cs
> +            if (existsCount > 0)
еще одна бизнес логическая валидация

2021-07-25 12:41 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicRepository.cs
> +            var entry = _context.Update(topic);
очень подозрительно, что у тебя на обновление передается topic, а не entity.
Тут точно код работает?)

2021-07-25 12:43 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicRepository.cs
> +            var entity = _mapper.Map<Entities.Topic>(topic);
в случае реализации логики обновления, нужно четко понимать какие поля могут быть затронуты при обновлении. В целом можно сделать так. На уровне сервиса разобрать какие поля изменятся и передать правильную модельку в репозиторий. В репозитории уже ничего не решать, а просто сделать маппинг в ентити, ну и сделать сохранение

2021-07-25 12:44 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicRepository.cs
> +            var entry = await _context.Topics.FirstOrDefaultAsync(x => x.Id.Equals(id));
Это не обязательно делать при удалении чего либо. Достаточно передать сущность правильного типа с определенным id

2021-07-25 12:44 UTC, pingvin1308 commented on TssT.DataAccess/Repositories/TopicRepository.cs
> +            var entry = await _context.Topics.FirstOrDefaultAsync(x => x.Id.Equals(id));
_context.Remove(new Entities.Topic { Id = id }); // как пример

2021-07-25 12:46 UTC, pingvin1308 requested changes
Еще я бы наверное не брался бы делать сразу все репозитории. Все проблема в том, что тебе на данном этапе совсем не понятно какие именно методы нужно будет вывести в репозитории. А выводить все подряд обычно не имеет смысла. Редко такое бывает, что в круд репозитории задействуются прямо все методы :)

2021-07-25 13:57 UTC, pingvin1308 approved these changes

2021-07-25 15:08 UTC, merged